package entities;
// Generated Jun 20, 2013 5:40:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="contactmanagementsystem"
)
public class Category  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private Set<Contacts> contactses = new HashSet<Contacts>(0);

    public Category() {
    }

    public Category(String categoryName, Set<Contacts> contactses) {
       this.categoryName = categoryName;
       this.contactses = contactses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="categoryId", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="categoryName", length=15)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="category")
    public Set<Contacts> getContactses() {
        return this.contactses;
    }
    
    public void setContactses(Set<Contacts> contactses) {
        this.contactses = contactses;
    }




}


