package entities;
// Generated Jun 5, 2013 5:07:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Contactlist generated by hbm2java
 */
public class Contactlist  implements java.io.Serializable {


     private Integer contactListId;
     private Integer myId;
     private Integer contactId;

    public Contactlist() {
    }

    public Contactlist(Integer myId, Integer contactId) {
       this.myId = myId;
       this.contactId = contactId;
    }
   
    public Integer getContactListId() {
        return this.contactListId;
    }
    
    public void setContactListId(Integer contactListId) {
        this.contactListId = contactListId;
    }
    public Integer getMyId() {
        return this.myId;
    }
    
    public void setMyId(Integer myId) {
        this.myId = myId;
    }
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }




}


