package entities;
// Generated Jun 24, 2013 4:38:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contactlist generated by hbm2java
 */
@Entity
@Table(name="contactlist"
    ,catalog="contactmanagementsystem"
)
public class Contactlist  implements java.io.Serializable {


     private Integer contactListId;
     private Employee employee;
     private Contacts contacts;
     private Set<Contactrelation> contactrelations = new HashSet<Contactrelation>(0);

    public Contactlist() {
    }

    public Contactlist(Employee employee, Contacts contacts, Set<Contactrelation> contactrelations) {
       this.employee = employee;
       this.contacts = contacts;
       this.contactrelations = contactrelations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="contactListId", unique=true, nullable=false)
    public Integer getContactListId() {
        return this.contactListId;
    }
    
    public void setContactListId(Integer contactListId) {
        this.contactListId = contactListId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empId")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contactId")
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="contactlist")
    public Set<Contactrelation> getContactrelations() {
        return this.contactrelations;
    }
    
    public void setContactrelations(Set<Contactrelation> contactrelations) {
        this.contactrelations = contactrelations;
    }




}


