package entities;
// Generated Jun 5, 2013 5:07:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Contactrelation generated by hbm2java
 */
public class Contactrelation  implements java.io.Serializable {


     private Integer contactRelationId;
     private Integer contactlistId;
     private Integer rating;
     private String notes;

    public Contactrelation() {
    }

    public Contactrelation(Integer contactlistId, Integer rating, String notes) {
       this.contactlistId = contactlistId;
       this.rating = rating;
       this.notes = notes;
    }
   
    public Integer getContactRelationId() {
        return this.contactRelationId;
    }
    
    public void setContactRelationId(Integer contactRelationId) {
        this.contactRelationId = contactRelationId;
    }
    public Integer getContactlistId() {
        return this.contactlistId;
    }
    
    public void setContactlistId(Integer contactlistId) {
        this.contactlistId = contactlistId;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


