package entities;
// Generated Jun 24, 2013 4:38:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="contactmanagementsystem"
)
public class Employee  implements java.io.Serializable {


     private Integer empId;
     private String empEmailId;
     private String password;
     private Set<Contactlist> contactlists = new HashSet<Contactlist>(0);

    public Employee() {
    }

    public Employee(String empEmailId, String password, Set<Contactlist> contactlists) {
       this.empEmailId = empEmailId;
       this.password = password;
       this.contactlists = contactlists;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="empId", unique=true, nullable=false)
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    
    @Column(name="empEmailId", length=78)
    public String getEmpEmailId() {
        return this.empEmailId;
    }
    
    public void setEmpEmailId(String empEmailId) {
        this.empEmailId = empEmailId;
    }
    
    @Column(name="password", length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Contactlist> getContactlists() {
        return this.contactlists;
    }
    
    public void setContactlists(Set<Contactlist> contactlists) {
        this.contactlists = contactlists;
    }




}


