package entities;
// Generated Jun 20, 2013 5:40:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="contactmanagementsystem"
    , uniqueConstraints = @UniqueConstraint(columnNames="empEmailId") 
)
public class Employee  implements java.io.Serializable {


     private int empId;
     private String empEmailId;
     private String password;
     private Set<Contactlist> contactlists = new HashSet<Contactlist>(0);

    public Employee() {
    }

	
    public Employee(int empId) {
        this.empId = empId;
    }
    public Employee(int empId, String empEmailId, String password, Set<Contactlist> contactlists) {
       this.empId = empId;
       this.empEmailId = empEmailId;
       this.password = password;
       this.contactlists = contactlists;
    }
   
     @Id 
    
    @Column(name="empId", unique=true, nullable=false)
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    
    @Column(name="empEmailId", unique=true, length=78)
    public String getEmpEmailId() {
        return this.empEmailId;
    }
    
    public void setEmpEmailId(String empEmailId) {
        this.empEmailId = empEmailId;
    }
    
    @Column(name="password", length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Contactlist> getContactlists() {
        return this.contactlists;
    }
    
    public void setContactlists(Set<Contactlist> contactlists) {
        this.contactlists = contactlists;
    }




}


