package entities;
// Generated Jun 20, 2013 5:40:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Interestbridge generated by hbm2java
 */
@Entity
@Table(name="interestbridge"
    ,catalog="contactmanagementsystem"
)
public class Interestbridge  implements java.io.Serializable {


     private Integer ibId;
     private Contacts contacts;
     private Interests interests;

    public Interestbridge() {
    }

    public Interestbridge(Contacts contacts, Interests interests) {
       this.contacts = contacts;
       this.interests = interests;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IB_id", unique=true, nullable=false)
    public Integer getIbId() {
        return this.ibId;
    }
    
    public void setIbId(Integer ibId) {
        this.ibId = ibId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contactId")
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="interestId")
    public Interests getInterests() {
        return this.interests;
    }
    
    public void setInterests(Interests interests) {
        this.interests = interests;
    }




}


