package entities;
// Generated Jun 5, 2013 5:07:43 PM by Hibernate Tools 3.2.1.GA

/**
 * Interestbridge generated by hbm2java
 */
public class Interestbridge implements java.io.Serializable {

    private Integer ibId;
    private Contacts contacts;
    private Interests interests;

    public Interestbridge() {
    }

    public Interestbridge(Contacts contacts, Interests interests) {
        this.contacts = contacts;
        this.interests = interests;
    }

    public Integer getIbId() {
        return this.ibId;
    }

    public void setIbId(Integer ibId) {
        this.ibId = ibId;
    }

    public Contacts getContacts() {
        return this.contacts;
    }

    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }

    public Interests getInterests() {
        return this.interests;
    }

    public void setInterests(Interests interests) {
        this.interests = interests;
    }
}
