package entities;
// Generated Jun 5, 2013 5:07:43 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Interests generated by hbm2java
 */
public class Interests  implements java.io.Serializable {


     private Integer interestId;
     private String interestName;
     private Set interestbridges = new HashSet(0);

    public Interests() {
    }

    public Interests(String interestName, Set interestbridges) {
       this.interestName = interestName;
       this.interestbridges = interestbridges;
    }
   
    public Integer getInterestId() {
        return this.interestId;
    }
    
    public void setInterestId(Integer interestId) {
        this.interestId = interestId;
    }
    public String getInterestName() {
        return this.interestName;
    }
    
    public void setInterestName(String interestName) {
        this.interestName = interestName;
    }
    public Set getInterestbridges() {
        return this.interestbridges;
    }
    
    public void setInterestbridges(Set interestbridges) {
        this.interestbridges = interestbridges;
    }




}


