package entities;
// Generated Jun 24, 2013 4:38:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Interests generated by hbm2java
 */
@Entity
@Table(name="interests"
    ,catalog="contactmanagementsystem"
)
public class Interests  implements java.io.Serializable {


     private Integer interestId;
     private String interestName;
     private Set<Interestbridge> interestbridges = new HashSet<Interestbridge>(0);

    public Interests() {
    }

    public Interests(String interestName, Set<Interestbridge> interestbridges) {
       this.interestName = interestName;
       this.interestbridges = interestbridges;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="interestId", unique=true, nullable=false)
    public Integer getInterestId() {
        return this.interestId;
    }
    
    public void setInterestId(Integer interestId) {
        this.interestId = interestId;
    }
    
    @Column(name="interestName", length=50)
    public String getInterestName() {
        return this.interestName;
    }
    
    public void setInterestName(String interestName) {
        this.interestName = interestName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="interests")
    public Set<Interestbridge> getInterestbridges() {
        return this.interestbridges;
    }
    
    public void setInterestbridges(Set<Interestbridge> interestbridges) {
        this.interestbridges = interestbridges;
    }




}


